#!/bin/bash
LANG=ru_RU.UTF-8
LC_ALL=ru_RU.UTF-8
export LANG
export LC_ALL

in_format="fb2"
out_format=$(basename ${0} | sed s/fb2//)

if [ -z "${CONV_LOG}" ]; then
    CONV_LOG="/dev/null"
else 
    if [ -d "${CONV_LOG}" ]; then
	CONV_LOG="$(realpath $CONV_LOG)/fb2conv.log"
    fi
    if [ ! -f "${CONV_LOG}" ]; then
	touch ${CONV_LOG}
    fi 
fi

run_path=$(dirname $(realpath ${0}))
converter="${run_path}/fb2c"

if [ ! -z "${1}" ]; then
    if  [ -f "${1}" ] ; then
	if [ ! -z "${2}" ] ; then
	    tmp_path=$(dirname $(realpath ${2}))
	    tmp_name=$(basename "${1}" | sed s/\.${in_format}$/\.${out_format}/)
	    if [ -d ${tmp_path} ] ; then
		if [ -x ${converter} ] ; then
		    echo "$(date +"%Y-%m-%dT%T.000%z")    INFO    Starting converstion from ${1} to ${2} via ${tmp_path}/${tmp_name}, by ${converter}:" >> ${CONV_LOG}
		    if [ -f ${tmp_path}/${tmp_name} ]; then
			echo "$(date +"%Y-%m-%dT%T.000%z")    INFO     Temporary file  ${tmp_path}/${tmp_name} is exist. Removing it!" >> ${CONV_LOG}
			rm -f ${tmp_path}/${tmp_name}  >> ${CONV_LOG}
		    fi
		    $converter --config ${run_path}/configuration.toml convert -to ${out_format} "${1}" "${tmp_path}" >> ${CONV_LOG} 
		    if [ -f "${tmp_path}/${tmp_name}" ]; then
			echo "$(date +"%Y-%m-%dT%T.000%z")    INFO    Converted temporary file  ${tmp_path}/${tmp_name} is found! Renaming to  ${2} ..." >> ${CONV_LOG}
			mv -f "${tmp_path}/${tmp_name}" ${2}  >> ${CONV_LOG} 2>&1 || exit 1
			echo "$(date +"%Y-%m-%dT%T.000%z")    INFO    Done!" >> ${CONV_LOG}
			exit 0
		    else
			echo "$(date +"%Y-%m-%dT%T.000%z")    INFO    Converted temporary file  ${tmp_path}/${tmp_name} is not found!" >> ${CONV_LOG}
			exit 1
		    fi
		else
		    echo "$(date +"%Y-%m-%dT%T.000%z")    INFO    Converter ${converter} is not found!" >> ${CONV_LOG}
		    exit 1
		fi
	    else
		echo "$(date +"%Y-%m-%dT%T.000%z")    INFO    Destination path ${tmp_path} is not found!" >> ${CONV_LOG}
		exit 1
	    fi
	else
	    echo "$(date +"%Y-%m-%dT%T.000%z")    INFO    Destination file ${2} is not defined!" >> ${CONV_LOG}
	    exit 1
	fi
    else
	echo "$(date +"%Y-%m-%dT%T.000%z")    INFO    Source file ${1} not found!" >> ${CONV_LOG}
	exit 1
    fi
else
    echo "$(date +"%Y-%m-%dT%T.000%z")    INFO    Source file ${1} is not defined!" >> ${CONV_LOG}
    exit 1
fi
